# Generated by Django 5.0.6 on 2024-06-20 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_carga', models.DateField(auto_now=True)),
            ],
        ),
    ]
